import './globals.css'
import { Inter } from 'next/font/google'

// This is the insertion point for our app and will determine what is rendered on all pages.
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Navbar */}
      <body className={inter.className}>{children}</body>
      {/* Footer */}
    </html>
  )
}
